import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <div className='flex h-full w-full rounded-xl shadow-lg z-10 bg-[#272d54]'>
          <Sidebar />
          <div className='flex flex-col w-full z-10 h-full ml-[90px]'>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
};

export default RootLayout;
