import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "YouTune",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang='en'>
      <body
        className={`${inter.className} flex h-full w-full min-h-[100dvh] overflow-x-hidden shadow-lg z-10 bg-[#272d54]`}
      >
        <Sidebar />
        <div className='flex flex-col w-full h-full pl-28 pr-8 pt-5 text-white'>
          {children}
        </div>
      </body>
    </html>
  );
};

export default RootLayout;
